const BAND_DATA_REQUEST = 'BAND_DATA_REQUEST';
const BAND_DATA_SUCCESS = 'BAND_DATA_SUCCESS';
const BAND_DATA_ERROR = 'BAND_DATA_ERROR';
const BAND_LIST_REQUEST = 'BAND_LIST_REQUEST';
const BAND_LIST_SUCCESS = 'BAND_LIST_SUCCESS';
const BAND_LIST_ERROR = 'BAND_LIST_ERROR';

export {
    BAND_DATA_REQUEST,
    BAND_DATA_SUCCESS,
    BAND_DATA_ERROR,
    BAND_LIST_REQUEST,
    BAND_LIST_SUCCESS,
    BAND_LIST_ERROR,
};